### ISSUE TITLE
[Feature Request] Skill Shop

### ISSUE THREAD

**Issue by JesterWizard** [FireEmblemUniverse/fe8u-cskillsys#2]
After skill scrolls I think this is the last big feature this system needs to reach parity with its predecessor. 

I've attempted numerous times to use the current skill scrolls implementation to stack  a shop with skills but only the first available skill ID is used and repeated.

**Comment by MokhaLeee** [comment]
https://github.com/FireEmblemUniverse/fe8u-cskillsys/commit/4a4aac2fb9bfc88a3193d3755a7b4eed2a114797
