### ISSUE TITLE
InitSturdy used in place of InitStrong in ifdef guard

### ISSUE THREAD

**Issue by JesterWizard** [FireEmblemUniverse/fe8u-cskillsys#3]
https://github.com/FireEmblemUniverse/fe8u-cskillsys/blob/988e09ff892e3c0682294b7feaaf994074358732/Wizardry/Core/SkillSys/MiscSkillEffects/ChapterInitSkills/Initiative.c#L8

**Comment by MokhaLeee** [comment]
https://github.com/FireEmblemUniverse/fe8u-cskillsys/commit/b87e54d18eafab7dea1501d014b10da6e1f8c5fe
